export default {
  about: [
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ullamcorper libero nec neque volutpat, id tristique ante blandit. Fusce dignissim erat vitae augue interdum vestibulum. Pellentesque vel nunc vel purus tristique eleifend.', 'In facilisis eros vel quam semper, sed egestas erat tincidunt. Donec bibendum sapien eu urna dapibus feugiat. Praesent et enim eget nulla volutpat sagittis a eget turpis. Sed auctor augue nec justo bibendum, nec sodales ligula tempor.', 'In hac habitasse platea dictumst. Curabitur congue nisl vel justo tincidunt bibendum. Integer nec rhoncus urna. Curabitur non malesuada urna.',
  ],
  projects: [
    {
      imageURL: 'https://www.scnsoft.com/blog-pictures/software-development-outsourcing/plan-your-project-with-your-software-development-methodology.png',
      title: 'Test Project',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ullamcorper libero nec neque volutpat, id tristique ante blandit. Fusce dignissim erat vitae augue interdum vestibulum.',
      technologies: ['React', 'Express', 'PostgreSQL'],
      projectLink: 'google.com',
    },
    {
      imageURL: 'https://www.scnsoft.com/blog-pictures/software-development-outsourcing/plan-your-project-with-your-software-development-methodology.png',
      title: 'Test Project',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ullamcorper libero nec neque volutpat, id tristique ante blandit. Fusce dignissim erat vitae augue interdum vestibulum.',
      technologies: ['React', 'Express', 'PostgreSQL'],
      projectLink: 'google.com',
    },
    {
      imageURL: 'https://www.scnsoft.com/blog-pictures/software-development-outsourcing/plan-your-project-with-your-software-development-methodology.png',
      title: 'Test Project',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ullamcorper libero nec neque volutpat, id tristique ante blandit. Fusce dignissim erat vitae augue interdum vestibulum.',
      technologies: ['React', 'Express', 'PostgreSQL'],
      projectLink: 'google.com',
    },
  ],
  experiences: [
    {
      startDate: 'MAY',
      endDate: 'SEPT 2023',
      title: 'DevOps Intern',
      company: 'Astera Labs',
      companySite: 'https://www.asteralabs.com/',
      description: 'Developed a dashboard for the company\'s AWS EC2 Spot Instances to save $20k+ annually by monitoring, identifying, and alerting occurences of resource waste or overprovisioning.',
      technologies: ['Python', 'React', 'Express', 'PostgreSQL', 'AWS', 'BitBucket', 'Jira'],
    },
    {
      startDate: '2022',
      endDate: 'APR 2023',
      title: 'Software Engineering Student',
      company: 'Hack Reactor',
      companySite: 'https://www.galvanize.com/hack-reactor/intermediate/full-time-bootcamp/#overview',
      description: '12-week advanced software engineering immersive program with 1000+ hours of coding in an AGILE environment.',
      technologies: ['JavaScript (ES5 and ES6)', 'React', 'TypeScript', 'Node', 'Express', 'jQuery', 'GraphQL', 'Redis', 'MySQL', 'PostgreSQL', 'MongoDB', 'Jest', 'Mocha', 'Chai', 'WebRTC', 'Socket.io', 'Webpack', 'Docker', 'AWS'],
    },
    {
      startDate: '2020',
      endDate: 'NOV 2022',
      title: 'Web Developer',
      company: 'Peak Performance Partners',
      companySite: 'https://www.3-peak.com/',
      description: 'Built custom WordPress sites using Elementor, JavaScript, and other front end technologies. Collaborated closely with clients to meet specific needs, ensuring tailored web solutions. Efficiently managed projects and met deadlines.',
      technologies: ['Wordpress', 'Elementor', 'Javascript', 'HTML', 'CSS'],
    },
    {
      startDate: '2021',
      endDate: 'MAR 2022',
      title: 'Tour Guide',
      company: 'MaxTour',
      companySite: 'https://www.maxtour.co',
      description: 'Guided groups to iconic sites, honing communication, organizational, and adaptability skills. Excelled in delivering exceptional experiences and expertly coordinated trips. Garnered 50+ 5-star reviews, propelling MaxTour to TripAdvisor\'s #1 spot for tours in Las Vegas.',
      technologies: ['Problem Solving', 'Communication', 'Leadership', 'Adaptability'],
    },
  ],
};
